### PR TITLE
Add 2D plot functions (save + alternative layout)

### PR DESCRIPTION
**Pull request by MathieuBo**
Good afternoon, 

Thanks a lot for developping bg-heatmaps. This is an excellent tool. 
I have implemented additional args for the 2D plotting function, just thought it could be useful to others. 

Additions:
- add a save function by passing a ```filename``` arg to ```heatmap.show()```
- ability to provide a colorbar label: ```cbar_label``` to ```heatmap.show()```
- ability to have "nude" plots with no axes (useful for illustration purposes): ```nude_plot=True``` (default is False) to```heatmap.show()```

Let me know if of interest to you and if you need edits. 
Cheers,
Mathieu

### CODE REVIEW

**Comment by FedeClaudi** [comment]
awesome thank you so much! That looks great and very useful. 

Only, can we change `nude_plot` to something more explicit like `hide_axes`?

**Comment by MathieuBo** [comment]
Great! I edited the arg name to ```hide_axes``` as suggested.

**Comment by FedeClaudi** [comment]
brilliant, I'll merge it thank you.

**Comment by FedeClaudi** [comment]
Published on pypi https://pypi.org/project/bgheatmap/

**Pull request merged**
